# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  binary: hashnode
  goos:
      - linux
      - darwin
      - windows
  goarch:
    - amd64
archive:
  name_template: "hashnode-{{ .Os }}-{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: hashnode
    name: hashnode-cli
  draft: false
brew:
  name: "hashnode"
  github:
    owner: hashnode
    name: homebrew-tap
  commit_author:
    name: goreleaserbot
    email: goreleaser@hashnode.com

  folder: Formula

  homepage: "https://hashnode.com"
  description: "Get hashnode.com on your terminal"
